- name: Add the OS specific variables
  include_vars: "../vars/keepalived.yml"
  when:
     -  ansible_hostname == "Haproxy01"

- name: Prerequisites
  include: tasks/prerequisites.yml



- name: install
  include: tasks/install.yml


