- name: Add the OS specific variables
  include_vars:  "{{ item }}"
  with_first_found:
    - keepalived.yml
    - haproxy.yml
    - ansible_hostname == "Haproxy01"


- name: Prerequisites
  include: tasks/prerequisites.yml
  when:
     - ansible_hostname == "Haproxy01"
     - ansible_hostname == "Haproxy02"

- name: install
  include: tasks/install.yml
  when:
     - ansible_hostname == "Haproxy01"
     - ansible_hostname == "Haproxy02"
