- name: Add the OS specific variables
  include_vars: "../vars/keepalived.yml"
  when:
     -  ansible_hostname == "Haproxy01"
     -  ansible_hostname == "Haproxy02"

- name: Prerequisites
  include: tasks/prerequisites.yml
  when:
     - ansible_hostname == "Haproxy01"
     - ansible_hostname == "Haproxy02"

- name: install
  include: tasks/install.yml
  when:
     - ansible_hostname == "Haproxy01"
     - ansible_hostname == "Haproxy02"
